name: flutter_ssi_wallet
description: Flutter Package for SSI Wallet
version: 0.0.1
author: Sarah Otto
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hive: 2.0.4
  bip32: 2.0.0
  bip39: 1.0.6
  web3dart: 2.3.1
  hex: 0.2.0
  crypto: 3.0.1
  uuid: 3.0.4
  json_schema2: 2.0.0+3
  asn1lib: 1.0.2


dev_dependencies:
  test: ^1.15.0
  test_process: ^2.0.0
  hive_generator: 1.1.1
  build_runner: 2.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

