name: flutter_ssi_wallet
description: Flutter Package for SSI Wallet
version: 0.0.1
author: Sarah Otto
homepage: https://credentials.hs-mittweida.de

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hive: 2.0.5
  bip32: 2.0.0
  bip39: 1.0.6
  dart_web3: ^0.0.3
  hex: 0.2.0
  crypto: 3.0.1
  uuid: 3.0.5
  json_schema2: 2.0.1+1
  asn1lib: 1.1.0


dev_dependencies:
  test: ^1.15.0
  test_process: ^2.0.0
  hive_generator: 1.1.2
  build_runner: 2.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

