name: dart_ssi
description: Dart Package supporting Verifiable Credentials, Dids, a wallet for them, Didcomm and IWCE
version: 1.0.2
repository: https://github.com/b2cm/dart_ssi/

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  hive: ^2.1.0
  bip32: ^2.0.0
  bip39: ^1.0.6
  web3dart: ^2.4.1
  crypto: ^3.0.2
  uuid: ^3.0.6
  json_schema2: ^2.0.2
  asn1lib: ^1.1.0
  crypto_keys: ^0.3.0
  elliptic: ^0.3.7
  x25519: ^0.1.1
  json_path: ^0.4.2
  base_codecs: ^1.0.1
  ed25519_edwards: ^0.3.1
  ed25519_hd_key: ^2.2.0
  json_ld_processor: ^1.0.0
  http: ^0.13.5



dev_dependencies:
  test: ^1.21.6
  test_process: ^2.0.3
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
  lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

